DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    roles TEXT NOT NULL
);

CREATE TABLE post(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    FOREIGN KEY (author_id) REFERENCES user(id)
);

CREATE TABLE barnehagen(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    navn TEXT UNIQUE NOT NULL,
    tilstand TEXT NOT NULL,
    mengde FLOAT NOT NULL,
    _type TEXT NOT NULL

);

CREATE TABLE hjemme(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    navn TEXT UNIQUE NOT NULL,
    tilstand TEXT NOT NULL,
    mengde FLOAT NOT NULL,
    _type TEXT NOT NULL

);

CREATE TABLE ting(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    navn TEXT UNIQUE NOT NULL,
    tilstand TEXT NOT NULL,
    mengde FLOAT NOT NULL,
    _type TEXT NOT NULL,
    lokasjon TEXT NOT NULL
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER NOT NULL,
    updated TIMESTAMP,
    updated_by_id INTEGER,
    updated_by_name TEXT
);

